#!/bin/sh

folder_app="/Applications/iHeadPhones.app/"
folder_data="/var/mobile/Documents/JypyzProducts/iHeadPhones/"
echo
echo Data folder: $folder_data
echo
echo Adjusting permissions...

chown -R root:wheel $folder_app
chmod 755 $folder_app
chown -R mobile:mobile $folder_data
chmod 775 $folder_data
chmod +x $folder_app/*.py
chmod +x $folder_app/start.sh

echo
echo Checking timezone...

if [ -f /etc/localtime ] ;then
        echo Timezone OK!
else
	echo Fixing timezone...
        ln -s /usr/share/zoneinfo/GMT /etc/localtime
fi

echo
echo Done!
